FROM bitnami/spark:latest

USER 0

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    && pip3 install pyspark \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV PYSPARK_PYTHON=python3

USER 1001