/* 1. 테이블 복사 REGION_RAW_DATA → REGION_AD_HOC */
-- ACTIVITY_CONSUME 테이블 AD_HOC으로 복사
DROP TABLE IF EXISTS REGION_AD_HOC.ACTIVITY_CONSUME;
CREATE TABLE REGION_AD_HOC.ACTIVITY_CONSUME AS
    SELECT *
    FROM REGION_RAW_DATA.ACTIVITY_CONSUME
    WHERE PAYMENT_DT_YMD < '2023-06-04';

-- LODGE_CONSUME 테이블 AD_HOC으로 복사
DROP TABLE IF EXISTS REGION_AD_HOC.LODGE_CONSUME;
CREATE TABLE REGION_AD_HOC.LODGE_CONSUME AS
    SELECT *
    FROM REGION_RAW_DATA.LODGE_CONSUME
    WHERE PAYMENT_DT_YMD < '2023-06-04';

-- META_ACTIVITY 테이블 AD_HOC으로 복사
DROP TABLE IF EXISTS REGION_AD_HOC.META_ACTIVITY;
CREATE TABLE REGION_AD_HOC.META_ACTIVITY AS
    SELECT *
    FROM REGION_RAW_DATA.META_ACTIVITY;

-- META_CODEA 테이블 AD_HOC으로 복사
DROP TABLE IF EXISTS REGION_AD_HOC.META_CODEA_DISTINCT;
CREATE TABLE REGION_AD_HOC.META_CODEA_DISTINCT AS
    SELECT IDX, CD_NM, CD_A, CD_MEMO, CD_MEMO2, 
        DEL_FLAG, ORDER_NUM, PERM_WRITE, PERM_EDIT,
        PERM_DELETE, INS_DT, EDIT_DT
    FROM REGION_RAW_DATA.META_CODEA
    WHERE REGION='CAPITAL';

-- META_CODEB 테이블 AD_HOC으로 복사
DROP TABLE IF EXISTS REGION_AD_HOC.META_CODEB_DISTINCT;
CREATE TABLE REGION_AD_HOC.META_CODEB_DISTINCT AS
    SELECT IDX, CD_NM, CD_A, CD_B, CD_MEMO, 
        DEL_FLAG, ORDER_NUM, INS_DT, EDIT_DT
    FROM REGION_RAW_DATA.META_CODEB
    WHERE REGION='CAPITAL';

-- META_SGG 테이블 AD_HOC으로 복사
DROP TABLE IF EXISTS REGION_AD_HOC.META_SGG_DISTINCT;
CREATE TABLE REGION_AD_HOC.META_SGG_DISTINCT AS
    SELECT DISTINCT *
    FROM REGION_RAW_DATA.META_SGG;

-- META_TRAVELLER_MASTER 테이블 AD_HOC으로 복사
DROP TABLE IF EXISTS REGION_AD_HOC.META_TRAVELLER_MASTER;
CREATE TABLE REGION_AD_HOC.META_TRAVELLER_MASTER AS
    SELECT *
    FROM REGION_RAW_DATA.META_TRAVELLER_MASTER;

-- MOVE 테이블 AD_HOC으로 복사
DROP TABLE IF EXISTS REGION_AD_HOC.MOVE;
CREATE TABLE REGION_AD_HOC.MOVE AS
    SELECT *
    FROM REGION_RAW_DATA.MOVE
    WHERE END_DT_YMD < '2023-06-04';

-- MVMN_CONSUME 테이블 AD_HOC으로 복사
DROP TABLE IF EXISTS REGION_AD_HOC.MVMN_CONSUME;
CREATE TABLE REGION_AD_HOC.MVMN_CONSUME AS
    SELECT *
    FROM REGION_RAW_DATA.MVMN_CONSUME
    WHERE PAYMENT_DT_YMD < '2023-06-04';

-- TRAVEL 테이블 AD_HOC으로 복사
DROP TABLE IF EXISTS REGION_AD_HOC.TRAVEL;
CREATE TABLE REGION_AD_HOC.TRAVEL AS
    SELECT *
    FROM REGION_RAW_DATA.TRAVEL
    WHERE TRAVEL_END_YMD < '2023-06-04';

-- 방문지 정보 테이블 AD_HOC으로 복사
DROP TABLE IF EXISTS REGION_AD_HOC.VISIT_AREA_INFO;
CREATE TABLE REGION_AD_HOC.VISIT_AREA_INFO AS
    SELECT *
    FROM REGION_RAW_DATA.VISIT_AREA_INFO
    WHERE VISIT_END_YMD < '2023-06-04';


/* 2. 지역 정보 파싱 & 데이터 정규화 
   2-1. 숙박 소비 내역 테이블 (LOGDGE_CONSUME) */
-- SIDO, SGG, SIDO_SGG 컬럼 추가
ALTER TABLE REGION_AD_HOC.LODGE_CONSUME
ADD COLUMN SIDO STRING;

ALTER TABLE REGION_AD_HOC.LODGE_CONSUME
ADD COLUMN SGG STRING;

ALTER TABLE REGION_AD_HOC.LODGE_CONSUME
ADD COLUMN SIDO_SGG STRING;

/* 2-2. 방문지 정보 테이블 (VISIT_AREA_INFO) */ 
-- SIDO, SGG, SIDO_SGG 컬럼 추가
ALTER TABLE REGION_AD_HOC.VISIT_AREA_INFO
ADD COLUMN SIDO STRING;

ALTER TABLE REGION_AD_HOC.VISIT_AREA_INFO
ADD COLUMN SGG STRING;

ALTER TABLE REGION_AD_HOC.VISIT_AREA_INFO
ADD COLUMN SIDO_SGG STRING;