/* 1. 테이블 복사 REGION_RAW_DATA → REGION_PROCESSED_DATA */

-- LODGE_CONSUME 테이블 PROCESSED_DATA으로 복사
DROP TABLE IF EXISTS REGION_PROCESSED_DATA.LODGE_CONSUME;
CREATE TABLE REGION_PROCESSED_DATA.LODGE_CONSUME AS
    SELECT *
    FROM REGION_RAW_DATA.LODGE_CONSUME
    WHERE PAYMENT_DT_YMD < '2023-06-04';

-- META_CODEA 테이블 PROCESSED_DATA으로 복사
DROP TABLE IF EXISTS REGION_PROCESSED_DATA.META_CODEA_DISTINCT;
CREATE TABLE REGION_PROCESSED_DATA.META_CODEA_DISTINCT AS
    SELECT IDX, CD_NM, CD_A, CD_MEMO, CD_MEMO2, 
        DEL_FLAG, ORDER_NUM, PERM_WRITE, PERM_EDIT,
        PERM_DELETE, INS_DT, EDIT_DT
    FROM REGION_RAW_DATA.META_CODEA
    WHERE REGION='capital';

-- META_CODEB 테이블 PROCESSED_DATA으로 복사
DROP TABLE IF EXISTS REGION_PROCESSED_DATA.META_CODEB_DISTINCT;
CREATE TABLE REGION_PROCESSED_DATA.META_CODEB_DISTINCT AS
    SELECT IDX, CD_NM, CD_A, CD_B, CD_MEMO, 
        DEL_FLAG, ORDER_NUM, INS_DT, EDIT_DT
    FROM REGION_RAW_DATA.META_CODEB
    WHERE REGION='capital';

-- META_SGG 테이블 PROCESSED_DATA으로 복사
DROP TABLE IF EXISTS REGION_PROCESSED_DATA.META_SGG_DISTINCT;
CREATE TABLE REGION_PROCESSED_DATA.META_SGG_DISTINCT AS
    SELECT DISTINCT *
    FROM REGION_RAW_DATA.META_SGG;

-- 방문지 정보 테이블 PROCESSED_DATA으로 복사
DROP TABLE IF EXISTS REGION_PROCESSED_DATA.VISIT_AREA_INFO;
CREATE TABLE REGION_PROCESSED_DATA.VISIT_AREA_INFO AS
    SELECT *
    FROM REGION_RAW_DATA.VISIT_AREA_INFO
    WHERE VISIT_END_YMD < '2023-06-04';


/* 2. 지역 정보 파싱 & 데이터 정규화 
   2-1. 숙박 소비 내역 테이블 (LOGDGE_CONSUME) */
-- SIDO, SGG, SIDO_SGG 컬럼 추가
ALTER TABLE REGION_PROCESSED_DATA.LODGE_CONSUME
ADD COLUMN SIDO STRING;

ALTER TABLE REGION_PROCESSED_DATA.LODGE_CONSUME
ADD COLUMN SGG STRING;

ALTER TABLE REGION_PROCESSED_DATA.LODGE_CONSUME
ADD COLUMN SIDO_SGG STRING;

/* 2-2. 방문지 정보 테이블 (VISIT_AREA_INFO) */ 
-- SIDO, SGG, SIDO_SGG 컬럼 추가
ALTER TABLE REGION_PROCESSED_DATA.VISIT_AREA_INFO
ADD COLUMN SIDO STRING;

ALTER TABLE REGION_PROCESSED_DATA.VISIT_AREA_INFO
ADD COLUMN SGG STRING;

ALTER TABLE REGION_PROCESSED_DATA.VISIT_AREA_INFO
ADD COLUMN SIDO_SGG STRING;